### ISSUE TITLE
arg and optenv - not working?

### ISSUE THREAD

**Issue by moriarty** [bponsler/roslaunch_to_dot#1]
We are using the `arg` tag with default values to launch robot specific files. The `default` value of the `arg` is then set using `optenv`. But this is does not work. 

For example:

```
<arg name="robot" default="$(optenv ROBOT !!NO_ROBOT_SET!!)"/> 
```

which should not launch if the arg hasn't been passed or set and will give the hint in the error message, or: 

```
 <arg name="robot" default="$(optenv ROBOT youbot-brsu-1)" />
```

I also tried overriding the args

```
./roslaunch-to-dot.py ~/ros_ws/.../ros/launch/btt.launch robot:=youbot-brsu-1 robot_env:=brsu-c025
```

The output (with file paths shortened) I get is:

```
WARNING: Could not locate launch file:  ~/ros_ws/.../mir_robots/mir_bringup/robots/$(optenv ROBOT !!NO_ROBOT_SET!!).launch
Traceback (most recent call last):
  File "./roslaunch-to-dot.py", line 1320, in <module>
    dot = launchFile.toDot()
  File "./roslaunch-to-dot.py", line 401, in toDot
    packageMap = self.getPackageMap()
  File "./roslaunch-to-dot.py", line 348, in getPackageMap
    packageName = launchFile.getPackageName()
  File "./roslaunch-to-dot.py", line 225, in getPackageName
    raise Exception("Failed to get package name for: %s" % self.__filename)
Exception: Failed to get package name for: ~/ros_ws/.../mir_robots/mir_bringup/robot.launch
ERROR: failed to generate dot file contents...
```

The line in `mir_bringup/robot.launch` which is failing is:

```
<include file="$(find mir_bringup)/robots/$(arg robot).launch" />
```

It is not taking the `robot:=youbot-brsu-1` or the environment variable which I have set correctly.

[Here is an example](https://github.com/mas-group/robocup-at-work/blob/brazil-2014/mas_industrial_robotics/mir_scenarios/mir_basic_transportation_test/ros/launch/btt.launch)  of an older version of the file I tested on with the entire project.

**Comment by bponsler** [comment]
Thanks for filing this.

The first problem is that the regular expression I was using for matching argument values did not account for !, and also apparently was not handling the default value to optenv correctly either.

I did notice a mistake in the command you ran, you wrote

```
./roslaunch-to-dot.py ~/ros_ws/.../ros/launch/btt.launch robot:=youbot-brsu-1 robot_env:=brsu-c025
```

However, that's missing the "outputFile" argument (the second argument) so it's trying to write a dot file name "robot:=youbot-brsu-1" which is why that argument value is not getting applied.

I am committing a fix for these issues right now so you should be able to grab them and get this working. I'll post back once I finish committing them just so you know.

**Comment by bponsler** [comment]
See commit 631589c0a20255cd3bcc1e19f7086a0ac8fd548a which should resolve these two problems for you. Let me know if you have more problems

**Comment by moriarty** [comment]
Thanks!

I did have a few more Issues, but I think all of them were on our end. Most of the issues are from our launch files not being in their expected locations.

**Comment by bit-pirate** [comment]
First, thanks for this tool! See great potential in it. Unfortunately at this point I cannot fully use it. Our launchers are fairly complex and we use lots of args and envs. When I attempt to convert one of our bigger launchers, I get many occurrences of the following error:

```
Traceback (most recent call last):
  File "./roslaunch-to-dot.py", line 728, in __parseLaunchElements
    self.__parseRosParam(child)
  File "./roslaunch-to-dot.py", line 881, in __parseRosParam
    resolved = self.__resolveText(paramFile)
  File "./roslaunch-to-dot.py", line 1005, in __resolveText
    resolved = substitutionFn(argument)
  File "./roslaunch-to-dot.py", line 1055, in __onEnvSubstitutionArg
    if arg not in environ:
NameError: global name 'arg' is not defined
```

It seems related to our usage of env, hence I'm attaching it to this thread. For example the below launcher throws the above error

```
<launch>
    <group ns="gopher">
        <group ns="configuration">
            <rosparam command="load" file="$(find gopher_configuration)/parameters/defaults.yaml"/>
            <rosparam command="load" file="$(find gopher_bootstrap)/parameters/configuration/$(env GOPHER_ROBOT).yaml"/>
        </group>
    </group>
</launch>
```

The first rosparam command is parsed fine, but the second, which has the env in it, throws the error.

**Comment by bponsler** [comment]
Thanks for reporting this, hopefully we can get the script to a point where it is usable for you (and others).

Looks like this bug was reintroduced by some other refactoring I did. I am about to commit a fix for the issue that should allow you to use environment variables.

**Comment by bit-pirate** [comment]
Awesome. Works well!
