### ISSUE TITLE
Can't parse conditional statements with eval

### ISSUE THREAD

**Issue by maximusnikulin** [bponsler/roslaunch_to_dot#13]
Hi, is there some way to parse conditional expression like this: 
`<arg name="max" value="$(find some_value)/path/visual.rviz" if="$(eval (env('MY_AIR') == 'AIRBUS' or env('MY_AIR') == 'BOING'))"/>` ?

**Comment by bponsler** [comment]
Nope, that has not been implemented yet. I’d gladly accept a PR to add this feature, but may have some time in the next couple weeks to add this.

Thanks for the suggestion.

**Comment by Erumeldor** [comment]
I would love to see this implemented. In our very big launch-stucture, many expressions are done with "eval". I sadly cannot use your tool therefore.

**Comment by bponsler** [comment]
Closing this issue since @Erumeldor fixed the issue (thanks!)
