### ISSUE TITLE
Does not handle launch files being included twice (in different namespaces)

### ISSUE THREAD

**Issue by dseifert** [bponsler/roslaunch_to_dot#4]
An error "There is a cycle in the launch file graph" happens when a launch file includes the same launch file multiple times (in different namespaces).

E.g.

```
<launch>
    <include file="$(find image_proc)/launch/image_proc.launch" ns="camera1" />
    <include file="$(find image_proc)/launch/image_proc.launch" ns="camera2" />
    <include file="$(find image_proc)/launch/image_proc.launch" ns="camera3" />
</launch>
```

One fix could be to add the namespace to the dot node's name. On the other hand, maybe the error message itself indicates an underlying problem? Technically speaking, this situation does not represent a cycle (a cycle would be A.launch including B.launch which includes A.launch) but rather duplicate paths which could simply be ignored.

P.S.: Maybe it would make things easier to use https://pygraphviz.github.io?

**Comment by bponsler** [comment]
That is definitely an interesting case I hadn't thought of.

I'm not sure at the moment how to handle this, other than (the obvious):

```
- provide a command line option to disable the checks for "cycles"
- remove the display of cycles all together (I'm still not entirely convinced it's something worth displaying)
```

The other way would be to uniquely identify the nodes using the namespace, but this would create three nodes in the graph (for your above example).

What do you think?

EDIT -- I forgot to say -- thanks for pointing me at pygraphviz. I'll definitely be updating things to use that.

**Comment by dseifert** [comment]
I believe you should check for cycles ... but this ain't one ;-) So this issue can be resolved by first fixing the cycle detection, and then to simply ignore duplicate edges between nodes (in pygraphviz this is rather easy by simply adding these edges with the same key, and only one will survive). Considering that your script wants to display dependencies between launch files (and nodes), I wouldn't add the namespaces.
